cgrc: add mode to monitor/report resource-usage stats for pre-exising scope/slice/cgroup-path

diff --git a/cgrc b/cgrc
--- a/cgrc
+++ b/cgrc
@@ -14,6 +14,7 @@ usage() {
 	bin=${0##*/}
 	echo >&2 "Usage: $bin [-x] [-r] { -l | -c | -p | -q [opts] } { -u unit | slice }"
 	echo >&2 "       $bin [-x] -v key[=value] { -u unit | slice }"
+	echo >&2 "       $bin [-x] -s { -u unit | slice | cgroup-path }"
 	echo >&2 "       $bin [-x] [run-opts] [-u unit] slice -- cmd [args...]"
 	echo >&2 "Run-opts: [-s] [-r] [-q [-i N] [-t N]] [-v key[=value]]"
 	echo >&2
@@ -32,6 +33,7 @@ usage() {
 	echo >&2 "-l - list all pids within specified slice recursively."
 	echo >&2 "-c - same as -l, but for exit code check: 35 = pids exist, 0 = empty."
 	echo >&2 "-s - print cgroup resource usage stats to stdout after running command."
+	echo >&2 "     Can be used w/o command to report stats for scope/slice/cgroup on ^C."
 	echo >&2 "-r - Run command as a terminal-connected service unit instead of scope."
 	echo >&2 "     Main diff is that forked pids will be killed after main one exits."
 	echo >&2 "-v - Show or set target cgroup parameter. Both key and value are raw strings."
@@ -47,6 +49,7 @@ usage() {
 	echo >&2 "  cgrc -l apps | xargs ps u"
 	echo >&2 "  cgrc -v cpu.max apps-pacman"
 	echo >&2 "  cgrc -v cpu.max='1500000 500000' apps-pacman"
+	echo >&2 "  cgrc -sru pulseaudio"
 	echo >&2
 	exit ${1:-1}
 }
@@ -75,9 +78,10 @@ shift $(($OPTIND - 1))
 cg=
 setcg() {
 	start=$1
-	local u
+	local u=''
 	[ -z "$cg" ] || return 0
 	[ -z "$slice" ] || {
+		[ "${slice#/sys/fs/cgroup/}" = "$slice" ] || { cg=${slice#/sys/fs/cgroup}; return 0; }
 		u=$slice; [ "${u%.slice}" != "$u" ] || u="${u}.slice"
 		[ -z "$start" ] || systemctl "$t" start "$u"; }
 	[ -z "$unit" ] || { u=$unit; [ "${u%.$mode}" != "$u" ] || u="${u}.$mode"; }
@@ -142,10 +146,11 @@ slice=$1
 }
 
 
-### run
-[ -n "$1" ] || usage 0
-[ "$1" = -- ] || { echo >&2 "ERROR - args where -- should be: $@"; usage; }
-shift; [ -n "$1" ] || { echo >&2 "ERROR - no command specified"; usage; }
+### run / stats-wrapper
+if [ -n "$1" ]; then
+	[ "$1" = -- ] || { echo >&2 "ERROR - args where -- should be: $@"; usage; }
+	shift; [ -n "$1" ] || { echo >&2 "ERROR - no command specified"; usage; }
+else [ -n "$stats" ] || usage 0; fi
 
 # Unit names should have no spaces, so command can be expanded from string
 [ -n "$unit" ] && u="--unit $unit" || { u=${1##*/}; u="--unit ${u%% *}"; }
@@ -156,12 +161,13 @@ wrapper="systemd-run -q $t $tu $u --slice $slice --"
 if [ -z "$stats" ]
 then exec $wrapper "$@"
 else
-	cg= unit=; setcg # finds slice path
+	cg=; setcg # finds slice path
 	[ -n "$cg" ] || {
 		u=$slice; [ "${u%.slice}" != "$u" ] || u="${u}.slice"
 		systemctl "$t" start "$u" || exit 1; setcg; }
 	[ -n "$cg" ] || { echo >&2 "ERROR - no slice for -s option"; exit 1; }
-	exec python3 "$0" "$cg" $wrapper "$@"
+	if [ -z "$1" ]; then exec python3 "$0" "$cg" - # stats from now to sigint
+	else exec python3 "$0" "$cg" $wrapper "$@"; fi
 fi
 
 
@@ -184,12 +190,15 @@ def print_stats_diff(ts_diff, s1, s2):
 	print('cgroup-stats:')
 	print(f'  time [s] :: {ts_diff:,.3f}')
 	for s in s1, s2:
-		s.cpu = adict(line.strip().split(None, 1) for line in s.cpu.split('\n') if line.strip())
-		s.io = adict( (k, adict(v.split('=', 1) for v in st.split()))
+		if s1.cpu: s.cpu = adict(
+			line.strip().split(None, 1) for line in s.cpu.split('\n') if line.strip() )
+		if s1.io: s.io = adict( (k, adict(v.split('=', 1) for v in st.split()))
 			for k, st in (line.strip().split(None, 1) for line in s.io.split('\n') if line.strip()) )
-	print('  cpu-time [s] ::', ' : '.join(
-		f'{rmsuff(k, "_usec")} {{:,.1f}}'.format((int(s2.cpu[k]) - int(v1)) / 1e6)
-		for k, v1 in s1.cpu.items() ))
+	if s1.cpu:
+		print('  cpu-time [s] ::', ' : '.join(
+			f'{rmsuff(k, "_usec")} {{:,.1f}}'.format((int(s2.cpu[k]) - int(v1)) / 1e6)
+			for k, v1 in s1.cpu.items() ))
+	if not s1.io: return
 	dev_map, p_dev = dict(), pl.Path('/dev/disk/by-label')
 	for p in p_dev.iterdir():
 		try:
@@ -213,12 +222,16 @@ def print_stats_diff(ts_diff, s1, s2):
 
 def main():
 	cmd, cg = sys.argv[2:], pl.Path('/sys/fs/cgroup') / sys.argv[1].strip('/')
+	if len(cmd) == 1 and cmd[0] == '-': cmd = None
 	stats = adict(dict.fromkeys('cpu io'.split()))
-	for p in stats: stats[p] = (cg / f'{p}.stat').read_text()
+	for p in list(stats):
+		try: stats[p] = (cg / f'{p}.stat').read_text()
+		except OSError: stats[p] = print(f'Skipping unavailable stats-group: {p}')
 	ts_diff = time.monotonic()
-	err = run(*cmd)
+	try: err = run(*cmd) if cmd else time.sleep(2**30)
+	except KeyboardInterrupt: err = print() or 130 # code when interrupting "sleep"
 	ts_diff = time.monotonic() - ts_diff
-	stats_new = adict((p, (cg / f'{p}.stat').read_text()) for p in stats)
+	stats_new = adict((p, (cg / f'{p}.stat').read_text()) for p, v in stats.items() if v)
 	print_stats_diff(ts_diff, stats, stats_new)
 	return err
 
@@ -227,5 +240,5 @@ except Exception as err:
 	print(
 		'ERROR - cgroup-stats wrapper failed:'
 		f' [{err.__class__.__name__}] {err}', file=sys.stderr )
-	sys.exit(1)
+sys.exit(1)
 EOF
