scraps: +ssh-direct-gue-tunnel

diff --git a/ssh-key-init b/ssh-key-init
--- a/ssh-key-init
+++ b/ssh-key-init
@@ -15,15 +15,14 @@ usage() {
 [[ "$1" = -h || "$1" = --help ]] && usage
 
 replace= machine= comment=
-while getopts "hrmc:" opt; do
-case "$opt" in
-		h) usage 0;;
-		r) replace=t;;
-		m) machine=t;;
-		c) comment="$OPTARG";;
-		*) echo >&2 -e "ERROR: Invalid option: -$OPTARG\n"; exit 1;;
-	esac
-done
+while getopts "hrmc:" opt
+do case "$opt" in
+	h) usage 0;;
+	r) replace=t;;
+	m) machine=t;;
+	c) comment=$OPTARG;;
+	*) echo >&2 -e "ERROR: Invalid option: -$OPTARG\n"; usage 1;;
+esac; done
 shift $((OPTIND-1))
 
 p="$1"
diff --git a/temp-patch b/temp-patch
--- a/temp-patch
+++ b/temp-patch
@@ -25,15 +25,14 @@ usage() {
 }
 
 rw= touch_before= touch_after=t
-while getopts ":hwtm" opt; do
-case "$opt" in
-		h) usage 0;;
-		w) rw=t;;
-		t) touch_before=t touch_after=;;
-		m) [[ -z "$touch_after" ]] && touch_after=t || touch_after=;;
-		*) echo >&2 -e "ERROR: Invalid option: -$OPTARG\n";;
-	esac
-done
+while getopts ":hwtm" opt
+do case "$opt" in
+	h) usage 0;;
+	w) rw=t;;
+	t) touch_before=t touch_after=;;
+	m) [[ -z "$touch_after" ]] && touch_after=t || touch_after=;;
+	*) echo >&2 -e "ERROR: Invalid option: -$OPTARG\n";;
+esac; done
 shift $((OPTIND-1))
 
 [[ "$#" -ge 2 && "$#" -le 3 ]] || { echo >&2 "ERROR: Invalid number of args ($#)"; exit 1; }
