vm.linux: update and sync with changes from ubuntu wrapper

diff --git a/vm/linux b/vm/linux
--- a/vm/linux
+++ b/vm/linux
@@ -1,34 +1,31 @@
 #!/bin/bash
 
 script_info='Generic linux distro VM with grub and partitioned disk img.'
+ins=1 mem=4G img= dev= iso=
+
+video=( -vga virtio -display gtk,gl=on )
+# video=( -vga std )
+# video=( -display vnc 0 )
+
+[[ "$1" = -r || "$1" = --root || "$UID" -ne 0 ]] || {
+	echo >&2 "ERROR: running as uid=0 but no -r/--root specified"; exit 1; }
+
+[[ "$1" = -i || "$1" = --instance ]] && { ins=$2; shift; shift; }
+[[ "$1" = -m || "$1" = --mem ]] && { mem=$2; shift; shift; }
+[[ "$1" = -q || "$1" = --img ]] && { img=$(realpath "$2"); shift; shift; }
+[[ "$1" = -d || "$1" = --dev ]] && { dev=$(realpath "$2"); shift; shift; }
+[[ "$1" = --iso ]] && { iso=$(realpath "$2"); shift; shift; }
+[[ "$1" = -c || "$1" = --console ]] && { video=( -nographic ); shift; }
+
+root=$(dirname "$BASH_SOURCE")
+dst="$root"/live.dump
+telnet_port=$(( 8200 + $ins ))
+vde_mac=52:54:00:12:34:$(( 60 + $ins ))
+vde_path=~/tmp/vde
+dump_inc= restore= net_only=
 
 
 ### Management
-
-root=/mnt/volatiles/vms
-dst="$root"/linux/live.dump
-telnet_port=8201
-vde_mac=52:54:00:12:34:61
-vde_path=~/tmp/vde
-dump_inc=
-restore=
-net_only=
-img=linux/install.qcow2.inc
-video=( -nographic )
-uid_root=
-
-[[ "$1" = -r || "$1" = --root ]] && { uid_root=t; shift; }
-[[ "$1" = -i || "$1" = --img ]] && { img=$(realpath "$2"); shift; shift; }
-
-[[ "$1" = -g || "$1" = --graphic ]] && {
-	video=( -vga std )
-	# video+=( -display gtk )
-	# video+=( -display vnc 0 )
-	shift
-}
-
-[[ "$UID" -ne 0 || -n "$uid_root" ]] \
-	|| { echo >&2 "ERROR: running as uid=0 but no -r/--root specified"; exit 1; }
 
 case "$1" in
 	d|dump)
@@ -69,8 +66,10 @@ EOF
 
 	'') ;;
 	*)
-		echo >&2 "Usage: $0 [-r|--root] [ {-i|--img} basename] [-g|--graphic] \\"
+		echo >&2 "Usage: $0 [-r|--root] [ {-i|--instance} $ins ] [ {-m|--mem} $mem ] \\"
+		echo >&2 "  [ {-q|--img} file.qcow2 ] [ {-d|--dev} /dev/xyz ] [ --iso image.iso ] [-c|--console] \\"
 		echo >&2 "  [ { d | dump } [path] | { r | restore } [-i] [path] | { m | monitor } | { n | net-only } ]"
+		echo >&2 "(note: ordering of options matters)"
 		cat >&2 <<EOF
 
 $script_info
@@ -88,6 +87,8 @@ Cheatsheet to init new cloudimg:
    && touch /mnt/nbd/etc/cloud/cloud-init.disabled
    && rm -rf /mnt/nbd/etc/systemd/system/cloud-init.target.wants
    && umount /mnt/nbd && qemu-nbd -d /dev/nbd0
+
+See vm/ubuntu for virtio-fs setup and info, not used here.
 
 EOF
 		exit 1 ;;
@@ -119,7 +120,7 @@ for n in {0..50}; do
 	[[ -e "$vde_path"/link.sock ]] && break
 	sleep 0.1
 done
-[[ $n -eq 50 ]] && { echo >&2 "vde switch startup failed"; exit 1; }
+[[ $n -lt 50 ]] || { echo >&2 "ERROR: vde switch startup failed"; exit 1; }
 
 cgrc -rcu vde-tap && {
 	cgrc -ru vde-tap apps-vm -- sudo vde_plug2tap \
@@ -137,12 +138,23 @@ done
 [[ -n "$net_only" ]] && exit 0
 
 
+### img/iso options
+
+root_opts=()
+[[ -z "$img" ]] || root_opts+=(
+	-drive file="$img",if=virtio,aio=native,cache=writeback,cache.direct=on )
+[[ -z "$dev" ]] || root_opts+=( -drive file="$dev",if=virtio,format=raw )
+
+[[ ${#root_opts[@]} -gt 0 ]] || { echo >&2 "virtio-fs setup is not supported here"; exit 1; }
+
+[[ -z "$iso" ]] || root_opts+=( -cdrom "$iso" )
+
+
 ### Run qemu
 
 qemu_opts=(
-	-name "$(basename "$0")"
+	-name "$(basename "$0").$ins"
 
-	-m 4096M
 	-rtc base=utc,clock=host
 	-monitor telnet:127.0.0.1:${telnet_port},server,nowait
 	-usb -device usb-kbd -device usb-mouse
@@ -153,13 +165,13 @@ qemu_opts=(
 	-enable-kvm
 	-cpu host
 	-smp 2
+	-m "$mem"
 	"${video[@]}"
+
+	"${root_opts[@]}"
 
 	# -device usb-ehci,id=usb,bus=pci.0,addr=0x4
 	# -device usb-host,hostbus=1,hostaddr=3
-
-	# -drive file="$img",if=virtio,aio=native,cache=writeback,cache.direct=on
-	# -cdrom ~/DLz/grml64-small_2018.12.iso
 )
 
 ulimit -c 0
@@ -167,4 +179,5 @@ export QEMU_AUDIO_DRV=none
 
 [[ -n "$restore" ]] && qemu_opts+=( -incoming "exec:bsdcat $dst" )
 
-exec cgrc -ru qemu-linux apps-vm -- qemu-system-x86_64 "${qemu_opts[@]}"
+exec cgrc -ru "qemu-linux@$ins" apps-vm \
+	-- qemu-system-x86_64 "${qemu_opts[@]}"
