vm.ubuntu: add -i/--instance switch

diff --git a/vm/ubuntu b/vm/ubuntu
--- a/vm/ubuntu
+++ b/vm/ubuntu
@@ -1,32 +1,31 @@
 #!/bin/bash
 
-script_info='Ubuntu VM, started from shared virtio-fs.'
+script_info='Ubuntu VM, started from shared virtio-fs by default.'
+ins=1 mem=4G img= dev= iso=
 
-
-### Management
-
-root=/mnt/volatiles/vms
-dst="$root"/ubuntu/live.dump
-telnet_port=8201
-vde_mac=52:54:00:12:34:61
-vde_path=~/tmp/vde
-dump_inc=
-restore=
-net_only=
-uid_root=
-img= dev= iso=
 video=( -vga virtio -display sdl,gl=on )
 # video=( -vga std )
 # video=( -display vnc 0 )
 
-[[ "$1" = -r || "$1" = --root ]] && { uid_root=t; shift; }
-[[ "$1" = -i || "$1" = --img ]] && { img=$(realpath "$2"); shift; shift; }
+[[ "$1" = -r || "$1" = --root || "$UID" -ne 0 ]] || {
+	echo >&2 "ERROR: running as uid=0 but no -r/--root specified"; exit 1; }
+
+[[ "$1" = -i || "$1" = --instance ]] && { ins=$2; shift; shift; }
+[[ "$1" = -m || "$1" = --mem ]] && { mem=$2; shift; shift; }
+[[ "$1" = -q || "$1" = --img ]] && { img=$(realpath "$2"); shift; shift; }
 [[ "$1" = -d || "$1" = --dev ]] && { dev=$(realpath "$2"); shift; shift; }
 [[ "$1" = --iso ]] && { iso=$(realpath "$2"); shift; shift; }
 [[ "$1" = -c || "$1" = --console ]] && { video=( -nographic ); shift; }
 
-[[ "$UID" -ne 0 || -n "$uid_root" ]] \
-	|| { echo >&2 "ERROR: running as uid=0 but no -r/--root specified"; exit 1; }
+root=/mnt/volatiles/vms
+dst="$root"/ubuntu/live.dump
+telnet_port=$(( 8200 + $ins ))
+vde_mac=52:54:00:12:34:$(( 60 + $ins ))
+vde_path=~/tmp/vde
+dump_inc= restore= net_only=
+
+
+### Management
 
 case "$1" in
 	d|dump)
@@ -67,8 +66,8 @@ EOF
 
 	'') ;;
 	*)
-		echo >&2 "Usage: $0 [-r|--root] \\"
-		echo >&2 "  [ {-i|--img} file.qcow2 ] [ {-d|--dev} /dev/xyz ] [ --iso image.iso ] [-c|--console] \\"
+		echo >&2 "Usage: $0 [-r|--root] [ {-i|--instance} $ins ] [ {-m|--mem} $mem ] \\"
+		echo >&2 "  [ {-q|--img} file.qcow2 ] [ {-d|--dev} /dev/xyz ] [ --iso image.iso ] [-c|--console] \\"
 		echo >&2 "  [ { d | dump } [path] | { r | restore } [-i] [path] | { m | monitor } | { n | net-only } ]"
 		echo >&2 "(note: ordering of options matters)"
 		cat >&2 <<EOF
@@ -208,9 +207,8 @@ root_opts=()
 ### Run qemu
 
 qemu_opts=(
-	-name "$(basename "$0")"
+	-name "$(basename "$0").$ins"
 
-	-m 4096M
 	-rtc base=utc,clock=host
 	-monitor telnet:127.0.0.1:${telnet_port},server,nowait
 	-usb -device usb-kbd -device usb-mouse
@@ -221,6 +219,7 @@ qemu_opts=(
 	-enable-kvm
 	-cpu host
 	-smp 2
+	-m "$mem"
 	"${video[@]}"
 
 	"${root_opts[@]}"
@@ -234,4 +233,5 @@ export QEMU_AUDIO_DRV=none
 
 [[ -n "$restore" ]] && qemu_opts+=( -incoming "exec:bsdcat $dst" )
 
-exec cgrc -ru qemu-ubuntu apps-vm -- qemu-system-x86_64 "${qemu_opts[@]}"
+exec cgrc -ru "qemu-ubuntu@$ins" apps-vm \
+	-- qemu-system-x86_64 "${qemu_opts[@]}"
