desktop.notifications.dev-nodes: add run/stop checks to pgrep processes
Via pseudo-device /pgrep[/opts]/name specs like:

  /pgrep/u/1001 stop uid-1001 processes
  /pgrep/firefox run start the browser
  /pgrep/uid=1000/redshift run de-session redshift should be running

With pgrep options in the middle auto-prefixed with -/--, if any.

diff --git a/desktop/notifications/dev-nodes b/desktop/notifications/dev-nodes
--- a/desktop/notifications/dev-nodes
+++ b/desktop/notifications/dev-nodes
@@ -49,6 +49,17 @@ check_dev() {
 			[[ "$st" =~ $re ]] && att_left=${BASH_REMATCH[2]} || att_left=0
 			[[ "$att_left" -lt "$att_chk" ]] || return 0 ;;
 
+		run|stop)
+			[[ "$dev" =~ ^/pgrep/(.+)$ ]] || {
+				echo >&2 "ERROR: Invalid pgrep spec '$dev $act ...'"; err=1; return; }
+			dev=${BASH_REMATCH[1]} a= ax= args=()
+			for a in ${dev//\// }; do [[ -z "$ax" ]] || {
+				[[ "${#ax}" -gt 1 ]] && args+=( --"$ax" ) || args+=( -"$ax" ); }
+				ax=$a; done; args+=( "$ax" )
+			pgrep "${args[@]}" >/dev/null && running=1 || running=
+			[[ "$act" != run ]] || { [[ -z "$running" ]] || return 0; }
+			[[ "$act" != stop ]] || { [[ -n "$running" ]] || return 0; } ;;
+
 		*) echo >&2 "ERROR: Unrecognized action '$dev $act ...'"; err=1; return
 	esac
 
